print('Írd be házi állat 1 nevét')
pet_name1 = input()
print('Írd be házi állat 2 nevét')
pet_name2 = input()
print('Írd be házi állat 3 nevét')
pet_name3 = input()
print('Írd be házi állat 4 nevét')
pet_name4 = input()
print('Írd be házi állat 5 nevét')
pet_name5 = input()
print('Írd be házi állat 6 nevét')
pet_name6 = input()

print(pet_name1 + ' '+ pet_name2 + ' '+pet_name3 + ' '+pet_name4 + ' '+pet_name5 + ' '+pet_name6)
